
<?php
$reviews = $this->getReviews();


?>
  


<!-- // var_dump($block->getgetHello()->getData()); -->


<?php
$reviews = $this->getReviews();


?>
  
  

    <?php foreach ($reviews as $review): ?>
    <div>
     <div class="sectionOne">
             <div>
             <h6><?php echo $review->getTitle_du_lien();?></h6>
                 <p maxlength="100"><?php echo $review->getDescription(); ?></p>
        
                <p><a href="<?php echo $review->getLien(); ?>">link</a></p>
             </div>

            <div>
                <img src="<?= $review->getIcone(); ?>" alt="<?= $review->getAlt(); ?>" width="100%" width="40px" height="40px"/>
            </div> 
   
                <!-- <img src="{{media url='../../../../../images/test.png ?>" /> -->
       </div>

       <div class="sectionTwo">
       <!-- <img src="{{view url="/EgioReinsurance/images/test.png"}}" /> -->

       </div>
      
   
    </div>


<?php endforeach; ?>

<!-- // var_dump($block->getgetHello()->getData()); -->

