<h2>Module de réassurance Magento2</h2>



<table>

  <tr>
         <th>Libelle</th>
          <th>Description</th>
          <th>Icone</th>
          <th>Alt</th>
          <th>Statut</th>
          <th>Ordre</th>
          <th>Lien</th>
          <th>Title du lien</th>
          <th>Nouvelle fenêtre</th>
          <th>Created At</th>
          <th>Updated At</th>
          <th>Action</th>
  </tr>



</table>